### ISSUE TITLE
This package will spoil you app!

### ISSUE THREAD

**Issue by ErunamoJAZZ** [jpoiri/ember-mx#1]
Hello, Im doing this issue, because this package broke my app (and I lost a lot of time trying to found what was the problem, but I dont have idea what happened hehehe).

In fact, i found some stuffs, first, in npmjs link to the repository does not exist (https://www.npmjs.com/package/ember-mx ), If you are maintaining this package, will be good idea if you update it.
Also, my app was useless like this one -> https://league-admin.herokuapp.com/

We use Ember 2.3.x, and ember-cli 1.13.15.

Idk what happened, so... good luck!

**Comment by jpoiri** [comment]
Hi, just let you know this old repo it has been moved to a private repo since am addon we build internally for the company i work for
